project_name: kubectl-services
release:
  github:
    owner: feloy
    name: kubectl-services
builds:
  - id: kubectl-services
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/feloy/kubectl-services/pkg/version.version=
archives:
  - id: kubectl-services
    builds:
    - kubectl-services
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
